apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: svea-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: local.svea.com
    http:
      paths:
      - path: /api/users
        pathType: Prefix
        backend:
          service:
            name: userservice
            port:
              number: 80
      - path: /api/timetracking
        pathType: Prefix
        backend:
          service:
            name: timetrackingservice
            port:
              number: 80